<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            ['name' => 'Badminton', 'slug' => 'badminton', 'icon' => '🏸', 'description' => 'Yonex, Li-Ning, Victor racquets, shuttles & accessories', 'product_count' => 12],
            ['name' => 'Tennis', 'slug' => 'tennis', 'icon' => '🎾', 'description' => 'Head, Babolat, Wilson racquets, balls & gut strings', 'product_count' => 8],
            ['name' => 'Cricket', 'slug' => 'cricket', 'icon' => '🏏', 'description' => 'SS, SG, MRF English Willow bats, pads & kit bags', 'product_count' => 10],
            ['name' => 'Football', 'slug' => 'football', 'icon' => '⚽', 'description' => 'Adidas, Nike, Puma studs, match balls & shin guards', 'product_count' => 6],
            ['name' => 'Indoor Shoes', 'slug' => 'shoes', 'icon' => '👟', 'description' => 'Asics, Yonex, Mizuno non-marking gum sole shoes', 'product_count' => 8],
            ['name' => 'Fitness & Gym', 'slug' => 'fitness', 'icon' => '🏋️', 'description' => 'Dumbbells, resistance bands, yoga mats & weights', 'product_count' => 5],
        ];

        foreach ($categories as $cat) {
            Category::updateOrCreate(['slug' => $cat['slug']], $cat);
        }

        $products = [
            [
                'code_id' => 'p1',
                'category' => 'badminton',
                'brand' => 'Yonex',
                'name' => 'Astrox 88D Pro Badminton Racquet',
                'price' => 14999,
                'old_price' => 17999,
                'rating' => 4.9,
                'reviews' => 214,
                'tag' => 'BESTSELLER',
                'specs' => '4U / G5 · Head Heavy · Stiff Shaft · Pre-String Option',
                'img' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p2',
                'category' => 'tennis',
                'brand' => 'Head',
                'name' => 'Head Speed MP 2024 Tennis Racquet',
                'price' => 18999,
                'old_price' => 22499,
                'rating' => 4.9,
                'reviews' => 189,
                'tag' => 'PRO CHOICE',
                'specs' => '300g · 100 sq.in · Auxetic 2.0 Tech · Unstrung Frame',
                'img' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p3',
                'category' => 'cricket',
                'brand' => 'SS',
                'name' => 'Ton Reserve Edition English Willow Bat',
                'price' => 12499,
                'old_price' => 15999,
                'rating' => 5.0,
                'reviews' => 312,
                'tag' => 'BESTSELLER',
                'specs' => 'Grade 1 Willow · Weight 1180g · Hand Oiled & Knocked',
                'img' => 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p4',
                'category' => 'badminton',
                'brand' => 'Li-Ning',
                'name' => 'Halbertec 7000 Badminton Racquet',
                'price' => 13599,
                'old_price' => 22990,
                'rating' => 4.8,
                'reviews' => 96,
                'tag' => 'NEW',
                'specs' => '3U / G5 · Even Balance · High Elasticity Carbon Shaft',
                'img' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p5',
                'category' => 'shoes',
                'brand' => 'Asics',
                'name' => 'Gel-Rocket 11 Non-Marking Indoor Shoes',
                'price' => 5499,
                'old_price' => 6999,
                'rating' => 4.8,
                'reviews' => 145,
                'tag' => 'BESTSELLER',
                'specs' => 'Gel Cushioning · Trusstic Tech · Non-Marking Gum Sole',
                'img' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p6',
                'category' => 'tennis',
                'brand' => 'Babolat',
                'name' => 'Pure Drive 2024 Tennis Racquet',
                'price' => 19499,
                'old_price' => 23999,
                'rating' => 4.9,
                'reviews' => 167,
                'tag' => 'POPULAR',
                'specs' => '300g · FSI Power Tech · High Power & Explosive Feel',
                'img' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p7',
                'category' => 'football',
                'brand' => 'Adidas',
                'name' => 'Predator Elite FG Football Boots',
                'price' => 8999,
                'old_price' => 11499,
                'rating' => 4.7,
                'reviews' => 342,
                'tag' => 'SALE',
                'specs' => 'Controlframe 2.0 · Moulded Studs · HybridTouch Upper',
                'img' => 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p8',
                'category' => 'badminton',
                'brand' => 'RSL',
                'name' => 'Tourney No.1 Feather Shuttlecocks (12 Pack)',
                'price' => 999,
                'old_price' => 1299,
                'rating' => 4.9,
                'reviews' => 410,
                'tag' => 'BESTSELLER',
                'specs' => 'Grade A Goose Feather · Speed 77 · Tournament Class',
                'img' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p9',
                'category' => 'cricket',
                'brand' => 'SG',
                'name' => 'Test Players Wicket Keeping Gloves',
                'price' => 3299,
                'old_price' => 3999,
                'rating' => 4.6,
                'reviews' => 84,
                'tag' => 'EQUIPMENT',
                'specs' => 'Premium Leather · Rubberized Palm Grip · Brass Thimbles',
                'img' => 'https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p10',
                'category' => 'fitness',
                'brand' => 'Cosco',
                'name' => 'Adjustable Rubber Dumbbell Set 20kg Kit',
                'price' => 4499,
                'old_price' => 5999,
                'rating' => 4.7,
                'reviews' => 78,
                'tag' => 'GYM ESSENTIAL',
                'specs' => 'Chrome Bar + Collars · Heavy Duty Rubber Coated Plates',
                'img' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p11',
                'category' => 'badminton',
                'brand' => 'Yonex',
                'name' => 'Nanoflare 800 Game Badminton Racquet',
                'price' => 11999,
                'old_price' => 14499,
                'rating' => 4.9,
                'reviews' => 134,
                'tag' => 'SPEED SERIES',
                'specs' => '4U / G5 · Head Light · Sonic Flare System · Deep Green',
                'img' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p12',
                'category' => 'tennis',
                'brand' => 'Head',
                'name' => 'Wilson Pro Staff 97 v14 Tennis Racquet',
                'price' => 21999,
                'old_price' => 25999,
                'rating' => 5.0,
                'reviews' => 92,
                'tag' => 'LEGENDARY',
                'specs' => '315g · 97 sq.in · Braid 45 Tech · Precision Control',
                'img' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p13',
                'category' => 'cricket',
                'brand' => 'SS',
                'name' => 'MRF Genius Grand Edition English Willow Bat',
                'price' => 18499,
                'old_price' => 21999,
                'rating' => 4.9,
                'reviews' => 245,
                'tag' => 'VIRAT SPECIAL',
                'specs' => 'Grade 1+ Willow · 1190g · Monster Edges & Massive Sweet Spot',
                'img' => 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p14',
                'category' => 'football',
                'brand' => 'Adidas',
                'name' => 'Nike Zoom Mercurial Superfly 9 FG',
                'price' => 14499,
                'old_price' => 17999,
                'rating' => 4.8,
                'reviews' => 178,
                'tag' => 'ELITE SPEED',
                'specs' => '3/4 Zoom Air Unit · Vaporposite+ Upper · Tri-Star Studs',
                'img' => 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p15',
                'category' => 'shoes',
                'brand' => 'Asics',
                'name' => 'Asics Court Control FF 2 Non-Marking',
                'price' => 9999,
                'old_price' => 12499,
                'rating' => 4.9,
                'reviews' => 112,
                'tag' => 'PRO BADMINTON',
                'specs' => 'FlyteFoam Technology · Twistruss Cushioning · Gum Rubber Sole',
                'img' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p16',
                'category' => 'badminton',
                'brand' => 'Li-Ning',
                'name' => 'Victor Thruster F Enhanced Edition Racquet',
                'price' => 16499,
                'old_price' => 19999,
                'rating' => 4.9,
                'reviews' => 88,
                'tag' => 'TAI TZU YING',
                'specs' => '4U / G5 · Power Box Frame · Free Core Synthetic Handle',
                'img' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p17',
                'category' => 'cricket',
                'brand' => 'SG',
                'name' => 'SG Sunny Gold Classic English Willow',
                'price' => 15999,
                'old_price' => 18999,
                'rating' => 4.8,
                'reviews' => 156,
                'tag' => 'CLASSIC EDITION',
                'specs' => 'Grade 1 Willow · Traditional Profile · Chevtec Grip',
                'img' => 'https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p18',
                'category' => 'tennis',
                'brand' => 'Babolat',
                'name' => 'Head Radical MP 2024 Tennis Racquet',
                'price' => 17999,
                'old_price' => 20999,
                'rating' => 4.7,
                'reviews' => 74,
                'tag' => 'VERSATILE',
                'specs' => '300g · Dynamic 16/19 String Pattern · Sound Grommets',
                'img' => 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p19',
                'category' => 'fitness',
                'brand' => 'Cosco',
                'name' => 'Heavy Duty 5-Level Resistance Band Set',
                'price' => 1499,
                'old_price' => 2299,
                'rating' => 4.8,
                'reviews' => 210,
                'tag' => 'WORKOUT KIT',
                'specs' => '100% Natural Latex · 10lbs to 50lbs · Includes Door Anchor',
                'img' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ],
            [
                'code_id' => 'p20',
                'category' => 'shoes',
                'brand' => 'Asics',
                'name' => 'Yonex Power Cushion 65 Z 3 Shoes',
                'price' => 11499,
                'old_price' => 13999,
                'rating' => 5.0,
                'reviews' => 320,
                'tag' => 'WORLD NO. 1',
                'specs' => 'Power Cushion+ · Radial Blade Sole · Feather Bounce Foam',
                'img' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80&auto=format&fit=crop',
                'img2' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80&auto=format&fit=crop',
                'in_stock' => true,
            ]
        ];

        foreach ($products as $p) {
            Product::updateOrCreate(['code_id' => $p['code_id']], $p);
        }
    }
}
